### ISSUE TITLE
[Bug] Pulverizer durability per diamond is 512 in the config instead of 1561

### ISSUE THREAD

**Issue by James103** [Pepperoni-Jabroni/PulverizerMod#1]
https://github.com/Pepperoni-Jabroni/PulverizerMod/blob/28651842c3eefb45c1e306fddc01ccc6436c28da/src/main/java/pepjebs/pulverizermod/config/PulverizerModConfig.java#L11
According to the readme, "Each diamond powers the Pulverizer for 1561 uses (the same amount as a Diamond Pickaxe has durability)." However, according to the above code, each diamond only powers the Pulverizer for 512 uses by default. Why is there this discrepancy?

Note: The actual value used defaults to 1561 if no config is present, as shown below:
https://github.com/Pepperoni-Jabroni/PulverizerMod/blob/08438d1e74c54a56c66a982b259b479791d90c20/src/main/java/pepjebs/pulverizermod/block/entity/PulverizerBlockEntity.java#L391-L394

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the report - I actually updated the base diamond durability to 512 in revision f82a99 and forgot to update the README. I'll need to update the reference in "PulverizerBlockEntity.java" as well. If you'd like to play with 1561, please simply update the value in your config. I personally thought that getting 1561 was too over-powered and unbalanced, so that's why I decreased it.
